# Generated by Django 3.1.7 on 2021-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='poll_count',
            field=models.IntegerField(null=True),
        ),
    ]
