# Generated by Django 3.1.7 on 2021-05-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210505_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='note',
            field=models.TextField(default=None, verbose_name='跟进内容...'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
