# Generated by Django 3.1.7 on 2021-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210505_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='跟进日期'),
        ),
    ]
