# Generated by Django 3.1.7 on 2021-05-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_classstudyrecord_student_studentstudyrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstudyrecord',
            unique_together={('student', 'classstudyrecord')},
        ),
    ]
