# Generated by Django 3.1.7 on 2021-05-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20210519_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(blank=True, null=True, verbose_name='成单日期'),
        ),
    ]
