# Generated by Django 3.1.7 on 2021-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20210520_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(null=True, to='app01.Role'),
        ),
    ]
