# Generated by Django 3.1.7 on 2021-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20210521_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='app01.Role'),
        ),
    ]
