# Generated by Django 3.1.7 on 2021-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20210521_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=32, verbose_name='权限名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64, verbose_name='权限路径'),
        ),
    ]
