# Generated by Django 3.1.7 on 2021-03-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
