# Generated by Django 3.1.7 on 2021-03-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pub_daye', models.DateTimeField()),
                ('pub_lish', models.CharField(max_length=32)),
            ],
        ),
    ]
